version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:prod
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: ${DB_HOST}
      MYSQL_DATA: /var/lib/mysql
    ports:
      - 3360:3360
    volumes:
      - mysql:/var/lib/mysql
networks:
  webnet:
volumes:
  mysql: